import type { Profile, ResultJson } from "./types.js";
import {
  getLlmClientForConfig,
  getLlmModelForConfig,
  type LlmRuntimeConfig,
} from "./llmClient.js";
import {
  compactLlmErrorForLog,
  isTransientLlmError,
  llmErrorStatus,
  logLlmApiErrorDetails,
  parseJsonLoose,
} from "./llmLog.js";
import { normalizeQuestion } from "./profileAnswers.js";
import { policyPromptBlock } from "./answerPolicies.js";

/**
 * Maps a job application form's fields to values, for the Tryvify extension's
 * "Fill" action. The extension harvests each field on the page into a
 * descriptor (with a self-minted `ref`), sends the batch here, and applies the
 * returned `ref -> value` map back onto the DOM. Selectors never leave the
 * browser — we only ever see text + refs.
 *
 * Two layers, cheapest first:
 *  1. Heuristic — standard fields (name, email, phone, links, location) matched
 *     from the profile by label/name/autocomplete keywords. Free, instant.
 *  2. AI — everything left over (open-text questions, custom dropdowns) answered
 *     in one batched LLM call using the run's answers + profile as context.
 */

/** One form field as harvested by the content script. */
export type FieldDescriptor = {
  ref: string;
  label?: string;
  name?: string;
  id?: string;
  placeholder?: string;
  ariaLabel?: string;
  autocomplete?: string;
  /** input type, or "textarea" / "select". */
  type?: string;
  /** Option labels for select / radio groups. */
  options?: string[];
  /** Nearby visible text (e.g. the question above a textarea). */
  surroundingText?: string;
};

export type FillValue = {
  ref: string;
  value: string;
  /**
   * Where the value came from:
   *  - "heuristic": a profile basic (name/email/…)
   *  - "app": this application's saved answer (result.json answers)
   *  - "profile": a profile-level reusable answer
   *  - "ai": freshly generated by the LLM
   * "app"/"profile" let the client save edits back to the right store.
   */
  source: "heuristic" | "app" | "profile" | "ai";
};

/**
 * The human question/label for a field — and the key we store/look up answers
 * under. The client mirrors this priority so saved answers match back to the
 * same field. Normalized (see normalizeQuestion) before use as a map key.
 */
export function questionOf(f: FieldDescriptor): string {
  return (f.label || f.ariaLabel || f.surroundingText || f.placeholder || f.name || "").trim();
}

function firstName(full: string): string {
  return full.trim().split(/\s+/)[0] ?? "";
}
function lastName(full: string): string {
  const parts = full.trim().split(/\s+/);
  return parts.length > 1 ? parts[parts.length - 1] : "";
}

/**
 * Standard profile fields, keyed by an EXACT (normalized) label match rather
 * than substring/regex. Exact matching avoids false positives like
 * "Who is your referrer's name?" or "Company name" getting the candidate's own
 * name just because the label contains "name". Labels are normalized first
 * (lowercased, punctuation collapsed to single spaces) so "E-mail Address *"
 * matches the "e mail address" alias. Add new phrasings to the alias lists.
 */
type StandardKey =
  | "email"
  | "phone"
  | "firstName"
  | "lastName"
  | "fullName"
  | "linkedin"
  | "github"
  | "portfolio"
  | "location"
  | "jobTitle"
  | "company";

const STANDARD_FIELD_ALIASES: Record<StandardKey, string[]> = {
  email: ["email", "email address", "e mail", "e mail address", "your email", "work email", "contact email"],
  phone: [
    "phone", "phone number", "phone no", "mobile", "mobile number", "mobile phone",
    "telephone", "telephone number", "cell", "cell phone", "contact number",
  ],
  firstName: ["first name", "given name", "legal first name", "preferred first name"],
  lastName: ["last name", "family name", "surname", "legal last name"],
  fullName: ["name", "full name", "your name", "your full name", "full legal name", "legal name", "candidate name", "applicant name"],
  linkedin: ["linkedin", "linkedin url", "linkedin profile", "linkedin profile url", "linkedin link"],
  github: ["github", "github url", "github profile", "github link"],
  portfolio: ["portfolio", "portfolio url", "portfolio website", "website", "website url", "personal website", "personal site", "url"],
  location: ["city", "location", "city state", "current location", "current city", "city and state"],
  jobTitle: [
    "job title", "current job title", "most recent job title", "current title", "most recent title",
    "position", "position title", "current position", "most recent position", "job position",
    "role", "current role", "your title", "title",
  ],
  company: [
    "company", "company name", "employer", "employer name", "current employer", "most recent employer",
    "current company", "most recent company", "your employer",
  ],
};

/**
 * "Title" is also a salutation field (Mr/Ms/Dr), which is virtually always a
 * select or radio group. Only treat it as a job title on a free-text input.
 */
function aliasAllowedForField(key: StandardKey, f: FieldDescriptor): boolean {
  if (key !== "jobTitle") return true;
  const bare = normalizeFieldLabel(f.label ?? f.ariaLabel ?? f.name);
  if (bare !== "title" && bare !== "role") return true;
  return f.type !== "select" && !(f.options && f.options.length > 0);
}

/**
 * Values reaching a form field, from ANY pass. Fixes two defects seen on every
 * application: the AI pass copying the resume header's "COMPANY | TITLE" into a
 * single box, and an ALL-CAPS name lifted from the rendered PDF heading.
 */
function sanitizeFillValues(fields: FieldDescriptor[], values: FillValue[]): FillValue[] {
  const keyByRef = new Map(fields.map((f) => [f.ref, classifyStandardField(f)]));
  return values.map((v) => {
    const key = keyByRef.get(v.ref);
    // Collapse the stray whitespace and newlines that come back from PDF text.
    let out = String(v.value ?? "").replace(/\s+/g, " ").trim();
    if (key === "jobTitle") {
      // "Trinnex | Senior Software Engineer" -> "Senior Software Engineer".
      // Only when a separator splits it into two non-empty halves.
      const m = /^(.+?)\s*[|\u2013\u2014]\s*(.+)$/.exec(out);
      if (m && m[2].trim()) out = m[2].trim();
    }
    if (key === "company") {
      // The mirror image: "Trinnex | Senior Software Engineer" -> "Trinnex".
      const m = /^(.+?)\s*[|\u2013\u2014]\s*(.+)$/.exec(out);
      if (m && m[1].trim()) out = m[1].trim();
    }
    if (key === "fullName" || key === "firstName" || key === "lastName" || key === "jobTitle") {
      // A name or job title in caps came from a rendered heading, not from the
      // profile. Company names are left alone: CIBC and ASSA ABLOY really are caps.
      if (out === out.toUpperCase() && /[A-Z]{2}/.test(out)) {
        out = out.toLowerCase().replace(/(^|[\s'\u2019-])([a-z])/g, (_, a, b) => a + b.toUpperCase());
      }
    }
    return out === v.value ? v : { ...v, value: out };
  });
}

/** normalized alias -> field key, built once from the alias table. */
const ALIAS_TO_KEY: Map<string, StandardKey> = (() => {
  const m = new Map<string, StandardKey>();
  for (const key of Object.keys(STANDARD_FIELD_ALIASES) as StandardKey[]) {
    for (const alias of STANDARD_FIELD_ALIASES[key]) m.set(alias, key);
  }
  return m;
})();

/**
 * Lowercase, drop "(required)/(optional)" style decorations, and collapse any
 * run of non-alphanumerics to a single space. So "First Name *",
 * "Email (required)", and "Phone Number:" normalize to clean aliases.
 */
function normalizeFieldLabel(s: string | undefined): string {
  return (s ?? "")
    .toLowerCase()
    .replace(/\([^)]*\)/g, " ") // strip parentheticals like "(required)"
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\b(required|optional)\b/g, " ") // stray required/optional markers
    .replace(/\s+/g, " ")
    .trim();
}

/** Exact machine signal: map the HTML autocomplete attribute's tokens to a key. */
function keyFromAutocomplete(ac: string | undefined): StandardKey | "" {
  const tokens = (ac ?? "").toLowerCase().split(/\s+/).filter(Boolean);
  if (tokens.includes("given-name")) return "firstName";
  if (tokens.includes("family-name")) return "lastName";
  if (tokens.includes("email")) return "email";
  if (tokens.some((t) => t === "tel" || t.startsWith("tel-"))) return "phone";
  if (tokens.includes("address-level2")) return "location";
  if (tokens.includes("url")) return "portfolio";
  if (tokens.includes("name")) return "fullName";
  return "";
}

/**
 * Classify a field to a standard key. The visible label (EXACT alias match)
 * wins; the autocomplete attribute is the fallback when no label alias matches.
 * Returns "" when the field is not a recognized standard field.
 */
function classifyStandardField(f: FieldDescriptor): StandardKey | "" {
  for (const raw of [f.label, f.ariaLabel, f.placeholder, f.name]) {
    const key = ALIAS_TO_KEY.get(normalizeFieldLabel(raw));
    if (key) return key;
  }
  return keyFromAutocomplete(f.autocomplete);
}

/** Match standard fields from the profile by exact label. Returns the matched
 * values plus the descriptors that still need the LLM. */
function heuristicPass(
  fields: FieldDescriptor[],
  profile: Profile,
): { values: FillValue[]; leftovers: FieldDescriptor[] } {
  const b = profile.basic;
  const full = b.fullName ?? "";
  const valueByKey: Record<StandardKey, string> = {
    email: b.email ?? "",
    phone: b.phone ?? "",
    firstName: firstName(full),
    lastName: lastName(full),
    fullName: full,
    linkedin: b.linkedin ?? "",
    github: b.github ?? "",
    portfolio: b.portfolio ?? "",
    location: b.location ?? "",
    jobTitle: profile.experience?.[0]?.title ?? b.title ?? "",
    company: profile.experience?.[0]?.company ?? "",
  };
  const values: FillValue[] = [];
  const leftovers: FieldDescriptor[] = [];
  for (const f of fields) {
    const key = classifyStandardField(f);
    const v = key && aliasAllowedForField(key, f) ? valueByKey[key] : "";
    if (v) values.push({ ref: f.ref, value: v, source: "heuristic" });
    else leftovers.push(f);
  }
  return { values, leftovers };
}

/**
 * Match leftover fields against previously-saved answers (profile reusable +
 * this application's stored answers, already merged by the caller with profile
 * precedence). No LLM — these are "instant"/Without-AI.
 */
function savedPass(
  fields: FieldDescriptor[],
  saved: Map<string, { answer: string; origin: "app" | "profile" }>,
): { values: FillValue[]; leftovers: FieldDescriptor[] } {
  const values: FillValue[] = [];
  const leftovers: FieldDescriptor[] = [];
  for (const f of fields) {
    const key = normalizeQuestion(questionOf(f));
    const hit = key ? saved.get(key) : undefined;
    if (hit && hit.answer) values.push({ ref: f.ref, value: hit.answer, source: hit.origin });
    else leftovers.push(f);
  }
  return { values, leftovers };
}

/** GPT-5 / o-series reject non-default temperature; omit for those. */
function temperatureParam(model: string, wanted: number): { temperature?: number } {
  const m = model.toLowerCase();
  if (m.startsWith("gpt-5") || /^o[1-9](-|$)/.test(m) || m.startsWith("openai/gpt-5") || /^openai\/o[1-9](-|$)/.test(m)) {
    return {};
  }
  return { temperature: wanted };
}

async function chatJson<T>(step: string, system: string, user: string, llm: LlmRuntimeConfig): Promise<T> {
  const client = getLlmClientForConfig(llm);
  const model = getLlmModelForConfig(llm);
  const messages = [
    { role: "system" as const, content: system },
    { role: "user" as const, content: user },
  ];
  const t0 = performance.now();
  console.log(`[enpply] LLM ▶ ${step} [json] provider=${llm.provider} model=${model} systemChars=${system.length} userChars=${user.length}`);
  // Set ENPPLY_LLM_IO=1 to dump the FULL prompt (system + user) — large (the JD
  // alone is ~16k chars), so it's off by default. The raw reply is always logged.
  if (process.env.ENPPLY_LLM_IO === "1") {
    console.log(`[enpply] LLM ▷ ${step} [json] SYSTEM ─────\n${system}\n[enpply] LLM ▷ ${step} [json] USER ─────\n${user}\n─────`);
  }
  const MAX_RETRIES = 2;
  // Start WITHOUT response_format. The json_object constraint narrows OpenRouter
  // to the providers that support structured output — a smaller pool that gets
  // rate-limited first (it's why a 429 hits a JSON call while the SAME model's
  // plain-text cover-letter call succeeds). We ask for JSON in the prompt and
  // parse the reply defensively; only if a reply comes back UNPARSEABLE do we
  // escalate to the hard json_object constraint to force valid JSON. Transient
  // failures (429 / 5xx) get exponential backoff — what the 429 body asks for.
  let useJsonMode = false;
  let lastErr: unknown;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const base = { model, messages, ...temperatureParam(model, 0.2) };
      const res = await client.chat.completions.create(
        useJsonMode ? { ...base, response_format: { type: "json_object" } } : base,
      );
      const text = res.choices[0]?.message?.content;
      if (!text) throw new Error("Empty model response");
      console.log(`[enpply] LLM ✓ ${step} [json] ${Math.round(performance.now() - t0)}ms replyChars=${text.length} jsonMode=${useJsonMode}`);
      console.log(`[enpply] LLM ◀ ${step} [json] raw reply:\n${text}`);
      try {
        return parseJsonLoose<T>(text);
      } catch (parseErr) {
        // Free-form reply wasn't JSON — escalate to forced structured output once.
        if (!useJsonMode && attempt < MAX_RETRIES) {
          console.warn(`[enpply] LLM ${step} [json] reply not JSON — retrying with response_format`);
          useJsonMode = true;
          continue;
        }
        throw parseErr;
      }
    } catch (e) {
      lastErr = e;
      if (attempt < MAX_RETRIES && isTransientLlmError(e)) {
        const waitMs = 700 * 2 ** attempt; // 700ms, 1400ms
        console.warn(`[enpply] LLM ${step} [json] transient ${llmErrorStatus(e) ?? "?"} — retry ${attempt + 1}/${MAX_RETRIES} in ${waitMs}ms`);
        await new Promise((r) => setTimeout(r, waitMs));
        continue;
      }
      break;
    }
  }
  console.warn(`[enpply] LLM ✗ ${step} [json] failed after ${Math.round(performance.now() - t0)}ms — ${compactLlmErrorForLog(lastErr)}`);
  logLlmApiErrorDetails(step, "json", lastErr);
  throw lastErr;
}

const FILL_SYSTEM = `You fill out a job application form on behalf of a candidate.
You are given the candidate's profile, the job context (job description plus the
application-form page text), and a list of unfilled form fields. Each field has
a "ref" id, a label/description, a type, and (for dropdowns/radios) an "options"
list.

Return STRICT JSON: { "values": [ { "ref": "<the field ref>", "value": "<text to enter>" }, ... ] }

Rules:
- ANSWER EVERY FIELD YOU REASONABLY CAN. Prefer a well-grounded answer over
  leaving a field blank. Use the profile, the reusable answers, and the job
  context together — reason from them, don't just copy:
  • "How many years of X / experience" → ESTIMATE from the dates and roles in the
    profile (e.g. earliest relevant role to now), and pick the matching range.
  • "Have you ever / are you currently / have you worked at <company>" (yes/no) →
    INFER from the profile; if no role matches the named company, the answer is
    the negative option.
  • Skill / tool / focus-area questions → choose what the profile's skills and
    experience support.
  • Open-text or scenario / technical questions (e.g. "walk us through how you
    would…") → answer them; they are expected, not optional.
- ANSWER STYLE for open-text fields: write the way a person SPEAKS — simple,
  everyday words and plain sentence structure. Keep each answer to 1–2 SHORT
  sentences. Write more ONLY when the question explicitly asks for a length or
  format (e.g. "in 200 words", "list three examples", "describe in detail").
  Ground it in the profile; no clichés or corporate filler.
- If a field has an "options" list, "value" MUST be one of those options, copied
  EXACTLY (same words, casing, punctuation). Pick the best-fitting option; only
  omit if truly none could apply.
- If a field's "type" is "checkboxes" it is MULTI-SELECT: return every applicable
  option as ONE string separated by " | ", e.g. "Machine learning | Data
  engineering". Each part must be an exact option.
- Reuse a reusable answer verbatim whenever a field asks the same thing.
- Do NOT fabricate specific facts you are not given: employers, titles, dates,
  degrees, exact metrics, salary, or work-authorization / visa / sponsorship
  status. OMIT a field ONLY when the profile genuinely gives you nothing to go on
  AND it asks for such a fact you must not guess.
- EXCEPTION — answering policies: if the context includes an "Answering policies"
  block, those user-set directives are authoritative and OVERRIDE the rule above.
  When a policy tells you how to DERIVE a value (e.g. a salary/comp figure
  computed from the posted range, or a stated default), compute it and enter it
  rather than leaving the field blank.
- Keep each value plain text suitable for a form input. No markdown.`;

/**
 * The job context the AI pass needs. Either derived from a stored run
 * (`jobContextFromResult`) or supplied directly by the caller (e.g. the
 * extension sending the current page's text when no run exists yet).
 */
export type JobContext = {
  company?: string;
  role?: string;
  role_summary?: string;
  key_requirements?: string[];
  job_description?: string;
  apply_form?: string;
};

export function jobContextFromResult(result: ResultJson): JobContext {
  return {
    company: result.company_name,
    role: result.role_name,
    role_summary: result.metadata?.role_summary,
    key_requirements: result.metadata?.key_requirements,
    job_description: typeof result.job_description === "string" ? result.job_description : "",
    apply_form: typeof (result as { apply_form?: unknown }).apply_form === "string" ? (result as { apply_form?: string }).apply_form : "",
  };
}

/** True when the context carries enough to answer open questions (JD or apply-form text). */
function hasJobContext(ctx: JobContext): boolean {
  return Boolean((ctx.job_description ?? "").trim() || (ctx.apply_form ?? "").trim());
}

/**
 * Profile for the fill prompt with experience bullets stripped. Bullets are the
 * bulk of the profile text and aren't needed to fill or answer form fields
 * (company, title, dates, skills, summary already give the model the facts), so
 * we drop them to keep the prompt small.
 */
function profileForFillPrompt(profile: Profile): Profile {
  return {
    ...profile,
    experience: profile.experience.map((exp) => {
      const copy = { ...exp };
      delete copy.bullets;
      return copy;
    }),
  };
}

function buildContext(
  profile: Profile,
  ctx: JobContext,
  reusable: Array<{ question: string; answer: string }> = [],
  policies: string[] = [],
): string {
  const jd = (ctx.job_description ?? "").trim();
  const applyForm = (ctx.apply_form ?? "").trim();
  const summary = (ctx.role_summary ?? "").trim();
  const reqs = (ctx.key_requirements ?? []).map((k) => (k ?? "").trim()).filter(Boolean);
  const hasMeta = Boolean(summary || reqs.length);

  const lines = [`Company: ${ctx.company || "(unknown)"}`, `Role: ${ctx.role || "(unknown)"}`];

  // When we'd otherwise send BOTH the raw JD and the raw apply-form text, treat
  // them as the same scrape if they're the same length (the run-free Q&A path
  // reuses the page for both) and keep only the form text — never ship ~the
  // whole page twice.
  const jdDupOfForm = Boolean(jd && applyForm && jd.length === applyForm.length);

  // Job context, cheapest first: the run's compact metadata (role summary + key
  // requirements) is enough to ground answers, so prefer it over the full JD.
  // Fall back to the full JD only when there's no metadata and it isn't a
  // duplicate of the form text; send nothing if we have neither.
  if (hasMeta) {
    if (summary) lines.push(`Role summary: ${summary}`);
    if (reqs.length) lines.push(`Key requirements:\n${reqs.map((k) => `- ${k}`).join("\n")}`);
  } else if (jd && !jdDupOfForm) {
    lines.push(`\nJob description:\n${jd}`);
  }

  if (applyForm) {
    lines.push(`\nApplication form / page text:\n${applyForm}`);
  }

  // Reusable answers the candidate has already given (EEO self-ID, work
  // eligibility, screening, etc.). Reuse these verbatim when a field asks the
  // same thing — they are authoritative over anything inferred from the profile.
  const known = reusable.filter((r) => r.answer && r.answer.trim());
  if (known.length) {
    lines.push(
      `\nReusable answers the candidate has already provided (reuse the SAME answer whenever a field asks the same thing; for option / checkbox fields pick the option that matches):\n${known
        .map((r) => `- ${r.question.trim()}: ${r.answer.trim()}`)
        .join("\n")}`,
    );
  }

  // Authoritative answering policies (salary derivation, acknowledgement
  // defaults, etc.). Placed before the profile so the model reads them as rules.
  const policyBlock = policyPromptBlock(policies);
  if (policyBlock) lines.push(policyBlock);

  lines.push(`\nCandidate profile JSON:\n${JSON.stringify(profileForFillPrompt(profile), null, 2)}`);
  return lines.join("\n");
}

/** Compact descriptor the model sees — ref + the human-meaningful bits only. */
function fieldForPrompt(f: FieldDescriptor) {
  return {
    ref: f.ref,
    label: f.label || f.ariaLabel || f.placeholder || f.name || "",
    type: f.type || "input",
    ...(f.options && f.options.length ? { options: f.options } : {}),
    ...(f.surroundingText ? { context: f.surroundingText } : {}),
  };
}

/** Normalize an option/answer for tolerant matching (case + spacing). */
function optNorm(s: string): string {
  return s.toLowerCase().replace(/\s+/g, " ").trim();
}

/**
 * Snap a model-returned value to one of the field's EXACT option strings.
 * Tolerant of case/spacing and near-misses (the model paraphrases), so "yes"
 * maps to "Yes" and "machine learning" to "Machine Learning". When one string
 * contains the other, prefer the shortest option so "Yes" beats "Yes, with
 * sponsorship". Returns the exact option text to enter, or null if no confident
 * match.
 */
function matchOption(opts: string[], value: string): string | null {
  const want = optNorm(value);
  if (!want) return null;
  const scored = opts.map((o) => ({ o, n: optNorm(o) })).filter((x) => x.n);
  const exact = scored.find((x) => x.n === want);
  if (exact) return exact.o;
  const contains = scored
    .filter((x) => x.n.includes(want) || want.includes(x.n))
    .sort((a, b) => a.n.length - b.n.length);
  return contains.length ? contains[0].o : null;
}

/**
 * Multi-select (checkbox-group) fields: split the model's value into the chosen
 * options and snap each to an exact option. Returns the distinct exact option
 * texts joined by " | " (the separator the extension splits on), or null if
 * none matched. Splits on | / ; / newline (not comma — options may contain one).
 */
function matchMultiOptions(opts: string[], value: string): string | null {
  const tokens = value.split(/\s*(?:\||;|\r?\n)\s*/).map((t) => t.trim()).filter(Boolean);
  const picks: string[] = [];
  for (const tok of tokens) {
    const m = matchOption(opts, tok);
    if (m && !picks.includes(m)) picks.push(m);
  }
  return picks.length ? picks.join(" | ") : null;
}

async function aiPass(
  leftovers: FieldDescriptor[],
  profile: Profile,
  ctx: JobContext,
  llm: LlmRuntimeConfig,
  reusable: Array<{ question: string; answer: string }> = [],
  policies: string[] = [],
): Promise<FillValue[]> {
  if (leftovers.length === 0) return [];
  const validRefs = new Set(leftovers.map((f) => f.ref));
  const optionsByRef = new Map(leftovers.filter((f) => f.options?.length).map((f) => [f.ref, f.options!]));

  const user = `${buildContext(profile, ctx, reusable, policies)}\n\nUnfilled form fields (answer what you can):\n${JSON.stringify(
    leftovers.map(fieldForPrompt),
    null,
    2,
  )}`;

  // What we asked the model to fill (compact — ref, type, label, #options).
  console.log(`[enpply] fill-map ▶ ${leftovers.length} field(s) sent to model:`);
  for (const f of leftovers) {
    const q = (f.label || f.surroundingText || f.name || "").replace(/\s+/g, " ").slice(0, 80);
    console.log(`  ${f.ref} [${f.type || "input"}]${f.options?.length ? ` opts=${f.options.length}` : ""} "${q}"`);
  }

  const raw = await chatJson<{ values?: Array<{ ref?: unknown; value?: unknown }> }>(
    "fill-map",
    FILL_SYSTEM,
    user,
    llm,
  );
  // Checkbox groups are multi-select; their value may name several options.
  const multiRefs = new Set(leftovers.filter((f) => f.type === "checkboxes").map((f) => f.ref));
  const out: FillValue[] = [];
  console.log(`[enpply] fill-map ◀ model returned ${raw.values?.length ?? 0} value(s):`);
  for (const item of raw.values ?? []) {
    const ref = String(item?.ref ?? "").trim();
    let value = String(item?.value ?? "").trim();
    if (!ref || !value || !validRefs.has(ref)) {
      const why = !ref ? "no ref" : !value ? "empty value" : "ref not on this page";
      console.log(`  ✗ ${ref || "(none)"}: "${value.slice(0, 60)}" — dropped (${why})`);
      continue;
    }
    // Snap option/dropdown answers to a real option. The model routinely
    // paraphrases or changes case, so a strict verbatim check left the field
    // blank; matchOption tolerates that. No confident match → omit (blank beats
    // entering a value the control can't accept).
    const opts = optionsByRef.get(ref);
    if (opts) {
      const matched = multiRefs.has(ref) ? matchMultiOptions(opts, value) : matchOption(opts, value);
      if (!matched) {
        const preview = opts.slice(0, 6).join(" | ") + (opts.length > 6 ? " | …" : "");
        console.log(`  ✗ ${ref}: "${value}" — matched no option of [${preview}]`);
        continue;
      }
      if (matched !== value) console.log(`  ~ ${ref}: "${value}" → option "${matched}"`);
      value = matched;
    }
    console.log(`  ✓ ${ref}: "${value.slice(0, 80)}"`);
    out.push({ ref, value, source: "ai" });
  }
  return out;
}

/**
 * Map fields to values.
 *  - mode "heuristic": instant, NO LLM. Returns standard-field matches plus the
 *    refs it couldn't match (so the client can offer an opt-in AI pass).
 *  - mode "ai": LLM only, over exactly the fields given (the client sends just
 *    the still-empty ones).
 *  - mode "both" (default): heuristic then AI over the leftovers (legacy path).
 */
export async function buildFillMap(params: {
  fields: FieldDescriptor[];
  profile: Profile;
  /**
   * Job context for the AI pass. From a stored run (jobContextFromResult) OR
   * supplied directly (e.g. the extension's current page text when no run
   * exists). The AI pass is skipped only when there is no usable context
   * (no JD and no apply-form text); the heuristic/saved passes need only the
   * profile, so "Easy Fill" still works with no context.
   */
  context?: JobContext;
  llm: LlmRuntimeConfig;
  mode?: "heuristic" | "ai" | "both";
  /**
   * Normalized-question → { answer, origin }. The caller merges this
   * application's saved answers (origin "app") with the profile's reusable
   * answers (origin "profile", taking precedence). Served with NO LLM, so they
   * count as "instant" / Without-AI; origin lets the client save edits back.
   */
  savedAnswers?: Map<string, { answer: string; origin: "app" | "profile" }>;
  /**
   * The profile's reusable answers (question + answer), passed to the AI pass as
   * context so the model reuses them verbatim when a field asks the same thing
   * (EEO self-ID, work eligibility, screening, etc.). Distinct from
   * `savedAnswers`, which the no-LLM passes apply directly by exact question.
   */
  reusableAnswers?: Array<{ question: string; answer: string }>;
  /**
   * The profile's enabled answering policies (free-text directives). Injected
   * into the AI pass as authoritative instructions — e.g. "compute salary as the
   * 80th percentile of the posted range". See answerPolicies.ts.
   */
  policies?: string[];
}): Promise<{ values: FillValue[]; unmatchedRefs: string[] }> {
  const mode = params.mode ?? "both";
  const saved = params.savedAnswers ?? new Map<string, { answer: string; origin: "app" | "profile" }>();
  const reusable = params.reusableAnswers ?? [];
  const policies = params.policies ?? [];

  const ctx = params.context;
  const ctxUsable = ctx ? hasJobContext(ctx) : false;

  if (mode === "ai") {
    let ai: FillValue[] = [];
    if (ctx && ctxUsable) {
      try {
        ai = await aiPass(params.fields, params.profile, ctx, params.llm, reusable, policies);
      } catch (e) {
        console.warn("[enpply] fill-map AI pass failed:", compactLlmErrorForLog(e));
      }
    } else {
      console.warn("[enpply] fill-map AI pass skipped: no job context (JD / apply-form text) available.");
    }
    const matched = new Set(ai.map((v) => v.ref));
    const unmatchedRefs = params.fields.map((f) => f.ref).filter((r) => !matched.has(r));
    return { values: sanitizeFillValues(params.fields, ai), unmatchedRefs };
  }

  // Run profile basics first, then apply saved (profile reusable) answers ON TOP
  // so a user-saved answer REWRITES the basic for the same field (e.g. an edited
  // "First Name" beats the auto-detected value). Both passes see every field;
  // last write per ref wins, and saved is written last.
  const { values: heuristic } = heuristicPass(params.fields, params.profile);
  const { values: savedValues } = savedPass(params.fields, saved);
  const byRef = new Map<string, FillValue>();
  for (const v of heuristic) byRef.set(v.ref, v);
  for (const v of savedValues) byRef.set(v.ref, v); // reusable rewrites the basic
  const instant = [...byRef.values()];
  const matchedRefs = new Set(byRef.keys());
  const leftovers = params.fields.filter((f) => !matchedRefs.has(f.ref));

  if (mode === "heuristic") {
    return { values: sanitizeFillValues(params.fields, instant), unmatchedRefs: leftovers.map((f) => f.ref) };
  }

  // mode "both": AI over whatever neither free pass could fill. With no usable
  // job context the AI pass is skipped (heuristic/saved stand).
  let ai: FillValue[] = [];
  if (leftovers.length > 0 && ctx && ctxUsable) {
    try {
      ai = await aiPass(leftovers, params.profile, ctx, params.llm, reusable, policies);
    } catch (e) {
      console.warn("[enpply] fill-map AI pass failed:", compactLlmErrorForLog(e));
    }
  }
  const matched = new Set([...instant, ...ai].map((v) => v.ref));
  const unmatchedRefs = params.fields.map((f) => f.ref).filter((r) => !matched.has(r));
  return { values: sanitizeFillValues(params.fields, [...instant, ...ai]), unmatchedRefs };
}
